import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ThemeProvider} from "@/components/theme-provider"
import {ModeToggle} from "@/components/modeToggle";
import Link from 'next/link'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <div className="flex justify-between p-5 items-center ">
                <div className="flex gap-5">
                    <Link
                        href="/user"
                        className="hover:bg-secondary rounded p-3"
                    >
                        User
                    </Link>
                    <Link
                        href="/product"
                        className="hover:bg-secondary rounded p-3"
                    >
                        Product
                    </Link>
                </div>
                <ModeToggle />
            </div>
            {children}
        </ThemeProvider>
        </body>
        </html>
    )
}
